### ISSUE TITLE
No compila

### ISSUE THREAD

**Issue by Pr0gmaT1k** [mvelasquezherrera/reddit#1]
Buenas tardes,

Estoy revisando el codigo y no compila porque faltan los `.xcproj` a las capas `Domain` y `Data` al repo.

Atte,

Julien.

**Comment by mvelasquezherrera** [comment]
> Buenas tardes,
> 
> Estoy revisando el codigo y no compila porque faltan los `.xcproj` a las capas `Domain` y `Data` al repo.
> 
> Atte,
> 
> Julien.

Buenas tardes, 

Que error sale? Porque tengo entendido que el proyecto igual funciona sin esos archivos en el repo. De hecho, en mi trabajo el repositorio lo manejamos de la misma manera y no he tenido problemas de compilarlo. Está clonando correctamente el repositorio?

Saludos

**Comment by cezhar** [comment]
Hola:

Prueba clonando tu mismo proyecto en una carpeta aparte, ideal sería saber si faltó agregar algún archivo al repo

Atte,

Cezhar

**Comment by cezhar** [comment]
<img width="1513" alt="Captura de Pantalla 2022-04-19 a la(s) 13 14 28" src="https://user-images.githubusercontent.com/19785528/164059210-4f63d733-d795-4cbd-85ef-26cf7d81654b.png">

**Comment by Pr0gmaT1k** [comment]
Gracias por su reactividad.

Hizé un clone y el repo no presenta ningun sub modulos. 
Los packages se synchronizan bien. 
Cuando se abre el `.xcworkspace`, encuentra el project `Reddit` pero no los `Domain` y `Data` que estan importados en el proyecto `Reddit` lo cual no puede funcionar sin la presencia de los repectivos `.xcproj`.
<img width="148" alt="imagen" src="https://user-images.githubusercontent.com/11977968/164059534-8b7eb7cd-33c4-49de-9134-47ec9e2f009e.png">

Como lo dice mi compañero @cezhar , te recomendo clonear tu propio proyecto en una carpeta aparte para reproducir el bloqueo.

Atte,

Julien.

**Comment by mvelasquezherrera** [comment]
Perdón si, error mío, ahora subo los archivos correspondientes

**Comment by mvelasquezherrera** [comment]
Acabo de subir ambos archivos, me confirma si lo pudieron compilar por fa

**Comment by cezhar** [comment]
> Acabo de subir ambos archivos, me confirma si lo pudieron compilar por fa
Hola:

He realizado pull al código y ahora compila, lo revisaremos con el equipo

Saludos y buen día

Cezhar

**Comment by mvelasquezherrera** [comment]
Perfecto, gracias

**Comment by Pr0gmaT1k** [comment]
Compila con `369fad01b6a2a148ae5d9fdb1621e1339c1834a4`, gracias.
